[package]
name = "particle-life"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive", "min_const_generics"] }
getrandom = { version = "0.2.3", features = ["js"] }
glam = { version = "0.19.0", features = ["bytemuck"] }
instant = { version = "0.1.11", features = ["wasm-bindgen"] }
log = "0.4.14"
palette = { version = "0.6.0", features = ["bytemuck"] }
rand = "0.8.4"
rand_distr = "0.4.2"
wgpu = { version = "0.11.0", features = ["webgl"] }
winit = { version = "0.25.0", features = ["web-sys"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
wasm-bindgen = "=0.2.78"
wasm-bindgen-futures = "0.4.28"
web-sys = { version = "0.3.55", features = ["Document", "Element", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9.0"
pollster = "0.2.4"

[profile.release]
debug = 1
