[package]
name = "particle-life"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive", "min_const_generics"] }
getrandom = { version = "0.2.7", features = ["js"] }
glam = { version = "0.21.3", features = ["bytemuck"] }
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
log = "0.4.17"
palette = { version = "0.6.1", features = ["bytemuck"] }
rand = "0.8.5"
rand_distr = "0.4.3"
wgpu = { version = "0.13.1", features = ["webgl"] }
winit = { git = "https://github.com/Liamolucko/winit.git", branch = "resize-observer2", features = ["css-size"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
# Keep this version in sync with .github/workflows/ci.yml
wasm-bindgen = "=0.2.82"
wasm-bindgen-futures = "0.4.32"
web-sys = { version = "0.3.59", features = ["Document", "Element", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9.0"
pollster = "0.2.5"

[profile.release]
debug = 1

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "step"
harness = false
