[package]
name = "particle-life"
version = "0.1.0"
authors = ["Liam Murphy <liampm32@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_distr = { version = "0.4", default-features = false }
macroquad = "0.3.0-alpha.14"
palette = { version = "0.5", default-features = false, features = ["std"] }
