[package]
name = "wgpu-test"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive", "min_const_generics"] }
env_logger = "0.9.0"
palette = { version = "0.6.0", features = ["bytemuck"] }
rand = "0.8.4"
rand_distr = "0.4.2"
wgpu = "0.10.1"
winit = { version = "0.25.0", features = ["web-sys"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wasm-bindgen-futures = "0.4.26"
web-sys = { version = "0.3.51", features = ["Document", "Element", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.12.0", features = ["rt-multi-thread"] }
