[package]
name = "particle-life"
version = "0.1.0"
authors = ["Liam Murphy <liampm32@gmail.com>"]
edition = "2018"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
palette = { version = "0.5" }
rand = { version = "0.8", features = ["getrandom"] }
rand_distr = { version = "0.4", default-features = false }
futures = { version = "0.3", features = ["executor"] }
serde = "1"

[dependencies.quicksilver]
git = "https://github.com/Liamolucko/quicksilver.git"
branch = "inline"
default-features = false
features = ["event-cache", "web-sys", "serde"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
web-sys = { version = "0.3", features = ["Document", "Element", "Worker", "AddEventListenerOptions", "DedicatedWorkerGlobalScope", "MessageEvent"] }
js-sys = "0.3.47"
console_error_panic_hook = "0.1"
serde_cbor = "0.11.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-channel = "1.5.1"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[package.metadata.wasm-pack.profile.profiling.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = true
