# Rust toolchain config for Netlify

[toolchain]
# Nightly is needed for WASM threading
channel = "nightly"
components = ["rustc", "cargo", "rust-std", "rust-src"]
targets = ["wasm32-unknown-unknown"]