name: ci
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: rustup target add wasm32-unknown-unknown
      - name: Format
        run: cargo fmt -- --check
      - name: Lint
        run: cargo clippy
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-bindgen
        run: |
          # Keep this version in sync with Cargo.toml
          curl -LO https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.91/wasm-bindgen-0.2.91-x86_64-unknown-linux-musl.tar.gz
          tar xzf wasm-bindgen-0.2.91-x86_64-unknown-linux-musl.tar.gz
          echo "$PWD/wasm-bindgen-0.2.91-x86_64-unknown-linux-musl" >> $GITHUB_PATH
      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen target/wasm32-unknown-unknown/release/particle-life.wasm --target web --out-dir pkg --no-typescript
          # Copy the artifacts we care about into a `pages` folder for upload.
          mkdir pages
          cp -r index.html pkg pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: pages
      - name: Deploy to GitHub Pages
        if: github.repository == 'Liamolucko/particle-life' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v1
